services:
  cipereusz-bot:
#    build: .
    image: suchencjusz/cipereusz:latest
    restart: always
    volumes:
      - ./cfg.json:/app/config_cipereusz.json:ro
      - ./cipereusz-bot-data:/cipereusz-bot-data
